name: Java CI with Gradle

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [ 17 ]
            fail-fast: true
        steps:
            -   name: Checkout
                uses: actions/checkout@v4.1.1
            -   name: Set up JDK ${{ matrix.java }}
                uses: actions/setup-java@v3.13.0
                with:
                    distribution: adopt
                    java-version: ${{ matrix.java }}
            -   name: Cache Gradle
                uses: actions/cache@v3.3.3
                with:
                    path: ~/.gradle
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: ${{ runner.os }}-gradle-
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Build
                run: ./gradlew build
            -   name: Upload JAR
                uses: actions/upload-artifact@v3.1.3
                with:
                    name: "🔨 Successfully build EternalPlots with JDK${{ matrix.jdk }}"
                    path: "build/libs/*.jar"
